-- Migración 020: Wizard de planificación de lanzamientos
-- Aplicar en Supabase SQL Editor

create table lanzamientos (
  id                         uuid primary key default gen_random_uuid(),
  created_by                 text,
  tipo                       text check (tipo in ('sku','marca','drop')),
  nombre                     text,
  familia                    text,
  metal                      text,
  marca                      text,
  precio_venta               numeric,
  coste                      numeric,
  margen_objetivo            numeric,
  clusters_objetivo          text[],
  n_tiendas                  integer,
  unidades_por_tienda        integer,
  distribucion_personalizada jsonb,
  semanas_rampa              integer,
  crecimiento_semanal_pct    numeric,
  factor_ajuste_pct          numeric,
  referencia_analoga         text,
  descuento_promo_pct        numeric,
  semanas_promo              integer,
  tipo_campana               text,
  notas_campana              text,
  escenarios                 jsonb,
  estado                     text check (estado in ('borrador','confirmado')) default 'borrador',
  paso_actual                integer default 1,
  output_unidades_total      integer,
  output_presupuesto_compra  numeric,
  output_margen_proyectado   numeric,
  output_breakeven_semanas   numeric,
  proveedor                  text,
  fecha_lanzamiento          date,
  lead_time_semanas          integer default 4,
  created_at                 timestamptz default now(),
  updated_at                 timestamptz default now()
);
